# Generated by Django 3.2 on 2021-09-01 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=30)),
                ('iconname', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('likes', models.IntegerField()),
                ('responses', models.IntegerField()),
                ('shared', models.IntegerField()),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('date_to_do', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('description', models.TextField(default='none description')),
                ('topic', models.TextField(blank=None, choices=[('unknown', 'Unknown'), ('Fund-raising', 'Funds'), ('Awareness', 'Awareness'), ('Meeting', 'Meeting')], default='unknown', max_length=40)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('race', models.CharField(max_length=30)),
                ('heigth', models.FloatField()),
                ('sex', models.CharField(max_length=30)),
                ('description', models.TextField(default='none description')),
                ('health_state', models.CharField(blank=None, choices=[('unknown', 'Unknown'), ('serious', 'Serious'), ('Stable', 'Stable'), ('Critical', 'Critical')], default='unknown', max_length=35)),
                ('publisher', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=30)),
                ('iconname', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('likes', models.IntegerField()),
                ('responses', models.IntegerField()),
                ('shared', models.IntegerField()),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('race', models.CharField(max_length=30)),
                ('heigth', models.FloatField()),
                ('sex', models.CharField(max_length=30)),
                ('description', models.TextField(default='none description')),
                ('health_state', models.CharField(blank=None, choices=[('unknown', 'Unknown'), ('serious', 'Serious'), ('Stable', 'Stable'), ('Critical', 'Critical')], default='unknown', max_length=35)),
                ('publisher', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
