# Generated by Django 3.2 on 2021-08-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('race', models.CharField(max_length=30)),
                ('heigth', models.FloatField()),
                ('sex', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=30)),
                ('iconname', models.CharField(max_length=30)),
                ('time', models.IntegerField()),
                ('content', models.TextField()),
                ('likes', models.IntegerField()),
                ('responses', models.IntegerField()),
                ('shared', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('race', models.CharField(max_length=30)),
                ('heigth', models.FloatField()),
                ('sex', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=30)),
                ('iconname', models.CharField(max_length=30)),
                ('time', models.IntegerField()),
                ('content', models.TextField()),
                ('likes', models.IntegerField()),
                ('responses', models.IntegerField()),
                ('shared', models.IntegerField()),
            ],
        ),
    ]
