# Generated by Django 3.2 on 2021-09-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
